### ISSUE TITLE
Make the title responsive

### ISSUE THREAD

**Issue by supertorpe** [GuillaumeSD/Freechess#1]
The title of the app is not responsive: on mobile it overflows to two lines:

![image](https://github.com/GuillaumeSD/Freechess/assets/1201504/eac1bcc5-a5f2-4cac-a782-278b543ff43c)

This should do the job:

```ts
const isSmallScreen = useMediaQuery(theme.breakpoints.down("sm"));
...
<Typography
	variant="h6"
	component="div"
	sx={{ flexGrow: 1, ml: 1, fontSize: isSmallScreen ? "1rem" : "1.25rem" }}
	>
	Free Chess
</Typography>
```

**Comment by GuillaumeSD** [comment]
It happens for screens below 366 pixels wide. I'll improve that in a future update. Thanks for the heads up 👍

**Comment by GuillaumeSD** [comment]
Fixed in [this commit](https://github.com/GuillaumeSD/Freechess/commit/5aba715fa89c8e1154b77bb86bc77fe020b9ec84).

Thanks again for the report @supertorpe 👍
